"""FICTIONAL demo edition content. Every name, place, outlet, figure, quote and
reference in this file is invented. The state of Itaquara and the city of
Porto Anil do not exist. Outlets are named by Greek letters on purpose so that
no reader can mistake them for real Brazilian outlets.

Three events, chosen to exercise the rules:
  E1 water emergency  - disputed figure with 3 sources, blind spot (low in pole A)
  E2 betting ads law  - sports-related exceptional inclusion with recorded reason,
                        blind spot (low in pole B)
  E3 building eviction - loaded terms (invasão/ocupação) in headlines, disputed
                        figure with 2 sources (table, not chart), two blind spots,
                        one per pole
"""

def T(pt, es, en):
    return {"pt": pt, "es": es, "en": en}


# code, nombre, tipo, alcance, region, audiencia, score on axis 1, 2, 3
# axis 1: negative = campo lulista, positive = campo bolsonarista
# axis 2: negative = centro-sul, positive = norte-nordeste
# axis 3: negative = institucionalista, positive = antissistema
OUTLETS = [
    ("alfa", "Diário Nacional Alfa", "diario", "nacional", "SE", 900_000, -0.35, -0.60, -0.50),
    ("beta", "Portal Beta", "digital", "nacional", "SE", 1_200_000, -0.55, -0.40, -0.30),
    ("gama", "TV Gama", "tv", "nacional", "SE", 3_000_000, -0.08, -0.50, -0.40),
    ("delta", "Revista Delta", "digital", "nacional", "S", 400_000, 0.60, -0.50, 0.50),
    ("epsilon", "Rádio Épsilon", "radio", "nacional", "SE", 1_500_000, 0.50, -0.30, 0.60),
    ("zeta", "Portal Zeta", "digital", "nacional", "CO", 700_000, 0.45, -0.25, 0.40),
    ("eta", "Jornal Eta do Nordeste", "diario", "regional", "NE", 300_000, -0.30, 0.70, -0.20),
    ("teta", "Portal Teta Amazônia", "digital", "regional", "N", 150_000, 0.30, 0.75, 0.20),
    ("iota", "Diário Iota", "diario", "regional", "NE", 250_000, -0.40, 0.60, -0.30),
    ("capa", "Rádio Capa Sertão", "radio", "regional", "NE", 200_000, 0.35, 0.65, 0.30),
    ("lambda", "Gazeta Lambda Sul", "diario", "regional", "S", 350_000, 0.40, -0.70, 0.10),
]
OFFICIAL_OUTLET = ("mu", "Agência Pública Mu", "agencia", "nacional", "CO", 0)
CI_HALF_WIDTH = 0.15

EDITION = {
    "numero": 0,
    "semana_inicio": "2026-09-28T00:00:00-03:00",
    "semana_fin": "2026-10-04T23:59:00-03:00",
    "corte_ingesta": "2026-10-02T23:59:00-03:00",
    "publicacion_prevista": "2026-10-05T06:00:00-03:00",
}

EVENTS = [
    # ------------------------------------------------------------------ E1
    {
        "slug": "itaquara-emergencia-hidrica",
        "seccion": "meio-ambiente", "secciones": ["meio-ambiente", "politica", "economia"],
        "impacto": 80, "sensible": False, "excepcional": False, "razon": None,
        "fecha": 1,
        "titulo": T("Itaquara decreta emergência hídrica em 14 municípios",
                    "Itaquara decreta emergencia hídrica en 14 municipios",
                    "Itaquara declares water emergency in 14 municipalities"),
        "articles": [
            ("alfa", 1, "Estiagem deixa milhares de famílias sem água e Itaquara decreta emergência"),
            ("beta", 1, "Seca histórica: 38 mil famílias sem água regular, diz federação rural"),
            ("eta", 2, "Emergência hídrica atinge 14 municípios; agricultores familiares pedem carro-pipa"),
            ("iota", 3, "Itaquara decreta emergência; Defesa Civil fala em 21,5 mil famílias afetadas"),
            ("delta", 3, "Com emergência, governo de Itaquara libera compras sem licitação por seis meses"),
            ("epsilon", 3, "TCE alerta para farra de contratos emergenciais em Itaquara"),
            ("zeta", 3, "Oposição vê cheque em branco em decreto de emergência hídrica"),
            ("teta", 2, "Decreto de emergência em Itaquara restringe irrigação e preocupa produtores"),
            ("capa", 3, "Itaquara: reservatórios em 11% e compras sem licitação"),
            ("lambda", 4, "Tribunal de Contas cobra transparência em compras emergenciais de Itaquara"),
            ("gama", 3, "Itaquara decreta emergência hídrica em 14 municípios"),
            ("mu", 1, "Governo de Itaquara publica decreto de emergência hídrica"),
        ],
        "claims": [
            {"codigo": "c-101", "tipo": "que", "primaria": "Diário Oficial do Estado de Itaquara, 29/09/2026 (fictício)",
             "texto": T("O governo do estado de Itaquara decretou situação de emergência hídrica em 14 municípios por 180 dias, em decreto publicado no Diário Oficial do Estado em 29 de setembro de 2026.",
                        "El gobierno del estado de Itaquara decretó situación de emergencia hídrica en 14 municipios por 180 días, en un decreto publicado en el Diario Oficial del Estado el 29 de septiembre de 2026.",
                        "The government of the state of Itaquara declared a water emergency in 14 municipalities for 180 days, in a decree published in the State Official Gazette on Sept. 29, 2026."),
             "fragmento": "O decreto de emergência hídrica, publicado nesta terça no Diário Oficial do Estado, vale por 180 dias em 14 municípios.",
             "supports": ["alfa", "beta", "eta", "iota", "delta", "epsilon", "zeta", "teta", "capa", "lambda", "gama", "mu"]},
            {"codigo": "c-102", "tipo": "que", "primaria": "Diário Oficial do Estado de Itaquara, 29/09/2026 (fictício)",
             "texto": T("O decreto restringe captações de água para irrigação acima de 50 metros cúbicos por hora e autoriza compras emergenciais sem licitação durante a vigência.",
                        "El decreto restringe las captaciones de agua para riego superiores a 50 metros cúbicos por hora y autoriza compras de emergencia sin licitación durante su vigencia.",
                        "The decree restricts irrigation water withdrawals above 50 cubic meters per hour and authorizes emergency purchases without competitive bidding while it is in force."),
             "fragmento": "O texto limita captações para irrigação acima de 50 m³/h e permite contratações emergenciais sem licitação.",
             "supports": ["alfa", "beta", "iota", "gama", "delta", "epsilon", "zeta", "teta", "capa"]},
            {"codigo": "c-103", "tipo": "cifra", "atribucion": "Defesa Civil estadual",
             "medida": T("famílias sem abastecimento regular de água", "familias sin abastecimiento regular de agua", "families without regular water supply"),
             "valor": 21500, "unidad": "famílias",
             "texto": T("A Defesa Civil estadual registrou 21.500 famílias sem abastecimento regular de água.",
                        "La Defensa Civil estatal registró 21.500 familias sin abastecimiento regular de agua.",
                        "The state civil defense agency recorded 21,500 families without regular water supply."),
             "fragmento": "Segundo boletim da Defesa Civil, 21.500 famílias estão sem abastecimento regular.",
             "supports": ["iota", "alfa", "gama", "capa"]},
            {"codigo": "c-104", "tipo": "cifra", "atribucion": "Federação dos Trabalhadores Rurais de Itaquara",
             "medida": T("famílias sem abastecimento regular de água", "familias sin abastecimiento regular de agua", "families without regular water supply"),
             "valor": 38000, "unidad": "famílias",
             "texto": T("A Federação dos Trabalhadores Rurais de Itaquara informou que 38.000 famílias estão sem abastecimento regular de água.",
                        "La Federación de Trabajadores Rurales de Itaquara informó que 38.000 familias están sin abastecimiento regular de agua.",
                        "The Itaquara Rural Workers' Federation said 38,000 families are without regular water supply."),
             "fragmento": "A federação rural contabiliza 38 mil famílias sem água regular nas áreas afetadas.",
             "supports": ["beta", "eta"]},
            {"codigo": "c-105", "tipo": "cifra", "atribucion": "Observatório da Água da Universidade Estadual de Itaquara",
             "medida": T("famílias sem abastecimento regular de água", "familias sin abastecimiento regular de agua", "families without regular water supply"),
             "valor": 29000, "unidad": "famílias",
             "texto": T("Um levantamento do Observatório da Água da Universidade Estadual de Itaquara estimou 29.000 famílias sem abastecimento regular de água.",
                        "Un relevamiento del Observatorio del Agua de la Universidad Estatal de Itaquara estimó 29.000 familias sin abastecimiento regular de agua.",
                        "A survey by the Water Observatory of Itaquara State University estimated 29,000 families without regular water supply."),
             "fragmento": "Levantamento do Observatório da Água estima 29 mil famílias afetadas.",
             "supports": ["alfa", "eta"]},
            {"codigo": "c-106", "tipo": "que", "primaria": "Tribunal de Contas do Estado de Itaquara, alerta de 01/10/2026 (fictício)",
             "texto": T("O Tribunal de Contas do Estado emitiu em 1º de outubro um alerta que recomenda a publicação das compras emergenciais em portal próprio em até 48 horas.",
                        "El Tribunal de Cuentas del Estado emitió el 1 de octubre una alerta que recomienda publicar las compras de emergencia en un portal propio en un plazo de 48 horas.",
                        "The State Audit Court issued an alert on Oct. 1 recommending that emergency purchases be published on a dedicated portal within 48 hours."),
             "fragmento": "O TCE recomendou que cada compra emergencial seja publicada em portal próprio em até 48 horas.",
             "supports": ["epsilon", "gama", "lambda", "delta", "zeta", "capa", "iota"]},
            {"codigo": "c-107", "tipo": "cita", "atribucion": "deputados da oposição na Assembleia Legislativa",
             "texto": T("Deputados da oposição na Assembleia Legislativa afirmaram que a dispensa de licitação abre margem para contratos sem controle.",
                        "Diputados de la oposición en la Asamblea Legislativa afirmaron que la dispensa de licitación abre margen para contratos sin control.",
                        "Opposition lawmakers in the state legislature said waiving competitive bidding leaves room for unchecked contracts."),
             "fragmento": "Para deputados da oposição, a dispensa de licitação abre margem para contratos sem controle.",
             "supports": ["zeta", "delta", "epsilon"]},
            {"codigo": "c-108", "tipo": "cita", "atribucion": "secretário estadual de Recursos Hídricos",
             "medida": None, "valor": 11, "unidad": "% da capacidade",
             "texto": T("O secretário estadual de Recursos Hídricos, Renato Albuquerque, disse que a medida é necessária porque os reservatórios estão com 11% da capacidade.",
                        "El secretario estatal de Recursos Hídricos, Renato Albuquerque, dijo que la medida es necesaria porque los embalses están al 11% de su capacidad.",
                        "State Water Resources Secretary Renato Albuquerque said the measure is necessary because reservoirs are at 11% of capacity."),
             "fragmento": "O secretário Renato Albuquerque disse que os reservatórios estão com 11% da capacidade.",
             "supports": ["alfa", "iota", "teta", "capa"]},
            {"codigo": "c-109", "tipo": "cuando",
             "texto": T("O estado registra chuvas abaixo da média desde maio, segundo o instituto estadual de meteorologia.",
                        "El estado registra lluvias por debajo del promedio desde mayo, según el instituto estatal de meteorología.",
                        "The state has recorded below-average rainfall since May, according to the state meteorological institute."),
             "fragmento": "As chuvas estão abaixo da média desde maio, segundo o instituto estadual de meteorologia.",
             "supports": ["alfa", "beta", "eta", "teta", "capa", "zeta"]},
        ],
        "brief": {
            "titulo": T("Itaquara decreta emergência hídrica em 14 municípios após meses de chuva abaixo da média",
                        "Itaquara decreta emergencia hídrica en 14 municipios tras meses de lluvias por debajo del promedio",
                        "Itaquara declares water emergency in 14 municipalities after months of below-average rain"),
            "paragraphs": [
                [(T("O governo do estado de Itaquara decretou situação de emergência hídrica em 14 municípios por 180 dias, segundo decreto publicado no Diário Oficial do Estado na terça-feira, 29 de setembro.",
                    "El gobierno del estado de Itaquara decretó situación de emergencia hídrica en 14 municipios por 180 días, según un decreto publicado en el Diario Oficial del Estado el martes 29 de septiembre.",
                    "The government of the state of Itaquara declared a water emergency in 14 municipalities for 180 days, according to a decree published in the State Official Gazette on Tuesday, Sept. 29."), ["c-101"]),
                 (T("O decreto restringe captações de água para irrigação acima de 50 metros cúbicos por hora e autoriza compras emergenciais sem licitação enquanto estiver em vigor.",
                    "El decreto restringe las captaciones de agua para riego superiores a 50 metros cúbicos por hora y autoriza compras de emergencia sin licitación mientras esté vigente.",
                    "The decree restricts irrigation water withdrawals above 50 cubic meters per hour and authorizes emergency purchases without competitive bidding while it is in force."), ["c-102"])],
                [(T("O estado registra chuvas abaixo da média desde maio, segundo o instituto estadual de meteorologia.",
                    "El estado registra lluvias por debajo del promedio desde mayo, según el instituto estatal de meteorología.",
                    "The state has recorded below-average rainfall since May, according to the state meteorological institute."), ["c-109"]),
                 (T("O secretário estadual de Recursos Hídricos, Renato Albuquerque, disse que a medida é necessária porque os reservatórios estão com 11% da capacidade.",
                    "El secretario estatal de Recursos Hídricos, Renato Albuquerque, dijo que la medida es necesaria porque los embalses están al 11% de su capacidad.",
                    "State Water Resources Secretary Renato Albuquerque said the measure is necessary because reservoirs are at 11% of capacity."), ["c-108"])],
                [(T("O número de famílias afetadas varia conforme a fonte: a Defesa Civil estadual registrou 21.500 famílias sem abastecimento regular; a Federação dos Trabalhadores Rurais de Itaquara informou 38.000; e um levantamento do Observatório da Água da Universidade Estadual de Itaquara estimou 29.000.",
                    "El número de familias afectadas varía según la fuente: la Defensa Civil estatal registró 21.500 familias sin abastecimiento regular; la Federación de Trabajadores Rurales de Itaquara informó 38.000, y un relevamiento del Observatorio del Agua de la Universidad Estatal de Itaquara estimó 29.000.",
                    "The number of affected families varies by source: the state civil defense agency recorded 21,500 families without regular water supply; the Itaquara Rural Workers' Federation reported 38,000; and a survey by the Water Observatory of Itaquara State University estimated 29,000."), ["c-103", "c-104", "c-105"])],
                [(T("Na quinta-feira, 1º de outubro, o Tribunal de Contas do Estado recomendou que as compras emergenciais sejam publicadas em portal próprio em até 48 horas.",
                    "El jueves 1 de octubre, el Tribunal de Cuentas del Estado recomendó publicar las compras de emergencia en un portal propio en un plazo de 48 horas.",
                    "On Thursday, Oct. 1, the State Audit Court recommended that emergency purchases be published on a dedicated portal within 48 hours."), ["c-106"]),
                 (T("Deputados da oposição na Assembleia Legislativa afirmaram que a dispensa de licitação abre margem para contratos sem controle.",
                    "Diputados de la oposición en la Asamblea Legislativa afirmaron que la dispensa de licitación abre margen para contratos sin control.",
                    "Opposition lawmakers in the state legislature said waiving competitive bidding leaves room for unchecked contracts."), ["c-107"])],
            ],
        },
        "commentary": True,
        "series": {"nombre": "Decretos de emergência por estiagem em Itaquara, 2016–2025 (fictício)",
                   "fuente": "Diário Oficial do Estado de Itaquara (série fictícia)",
                   "datos": [{"ano": y, "decretos": v} for y, v in
                             [(2016, 1), (2017, 0), (2018, 0), (2019, 1), (2020, 0), (2021, 1), (2022, 0), (2023, 0), (2024, 1), (2025, 0), (2026, 1)]]},
    },
    # ------------------------------------------------------------------ E2
    {
        "slug": "itaquara-publicidade-apostas",
        "seccion": "economia", "secciones": ["economia", "politica", "sociedade"],
        "impacto": 65, "sensible": False, "excepcional": True,
        "razon": T("Tema esportivo incluído por exceção: regulação estadual de publicidade com efeito declarado sobre o endividamento das famílias e a arrecadação pública.",
                   "Tema deportivo incluido por excepción: regulación estatal de publicidad con efecto declarado sobre el endeudamiento de los hogares y la recaudación pública.",
                   "Sports-related topic included by exception: state advertising regulation with a stated effect on household debt and public revenue."),
        "fecha": 2,
        "titulo": T("Assembleia de Itaquara aprova restrição à publicidade de apostas esportivas",
                    "Asamblea de Itaquara aprueba restricción a la publicidad de apuestas deportivas",
                    "Itaquara legislature approves limits on sports betting advertising"),
        "articles": [
            ("alfa", 2, "Itaquara aprova lei contra publicidade de bets; 18% dos endividados citam apostas"),
            ("beta", 3, "Bets: pesquisa liga apostas a dívida de famílias em Itaquara"),
            ("iota", 2, "Assembleia de Itaquara restringe anúncios de apostas por 31 a 12"),
            ("eta", 3, "Lei estadual limita propaganda de apostas na TV e no rádio"),
            ("delta", 2, "Assembleia de Itaquara aprova lei que tira R$ 48 milhões do caixa do estado"),
            ("epsilon", 3, "Setor de apostas vai à Justiça contra lei de Itaquara"),
            ("zeta", 2, "Lei de Itaquara contra bets ameaça receita de emissoras locais, dizem deputados"),
            ("lambda", 3, "Itaquara proíbe anúncio de apostas das 6h às 22h"),
            ("capa", 3, "Rádios do interior temem perder anúncios com lei das apostas"),
            ("teta", 4, "Assembleia aprova restrição à publicidade de apostas; texto vai a sanção"),
            ("gama", 2, "Itaquara aprova restrição à publicidade de apostas esportivas"),
        ],
        "claims": [
            {"codigo": "c-201", "tipo": "que", "primaria": "Ata da sessão da Assembleia Legislativa de Itaquara, 30/09/2026 (fictício)",
             "texto": T("A Assembleia Legislativa de Itaquara aprovou em 30 de setembro de 2026, por 31 votos a 12, o projeto de lei estadual 214/2026, que restringe a publicidade de apostas esportivas de quota fixa.",
                        "La Asamblea Legislativa de Itaquara aprobó el 30 de septiembre de 2026, por 31 votos contra 12, el proyecto de ley estatal 214/2026, que restringe la publicidad de apuestas deportivas de cuota fija.",
                        "The Itaquara state legislature approved state bill 214/2026, which restricts advertising of fixed-odds sports betting, by 31 votes to 12 on Sept. 30, 2026."),
             "fragmento": "O projeto 214/2026 foi aprovado por 31 votos a 12 na sessão de quarta-feira.",
             "supports": ["alfa", "beta", "iota", "eta", "delta", "epsilon", "zeta", "lambda", "capa", "teta", "gama"]},
            {"codigo": "c-202", "tipo": "que", "primaria": "Texto aprovado do PL 214/2026 (fictício)",
             "texto": T("O texto proíbe anúncios de apostas em rádio e televisão entre 6h e 22h e em eventos esportivos realizados em equipamentos públicos estaduais.",
                        "El texto prohíbe anuncios de apuestas en radio y televisión entre las 6 y las 22 horas y en eventos deportivos realizados en instalaciones públicas estatales.",
                        "The text bans betting ads on radio and television between 6 a.m. and 10 p.m. and at sporting events held in state-owned public venues."),
             "fragmento": "Ficam proibidos anúncios de apostas no rádio e na TV entre 6h e 22h e em eventos em equipamentos estaduais.",
             "supports": ["eta", "lambda", "iota", "teta", "gama", "alfa", "capa"]},
            {"codigo": "c-203", "tipo": "que", "primaria": "Regimento e Constituição do Estado de Itaquara (fictício)",
             "texto": T("O projeto segue para sanção ou veto do governador, que tem 15 dias úteis para decidir.",
                        "El proyecto pasa a la sanción o el veto del gobernador, que tiene 15 días hábiles para decidir.",
                        "The bill goes to the governor, who has 15 business days to sign or veto it."),
             "fragmento": "O texto vai a sanção; o governador tem 15 dias úteis para sancionar ou vetar.",
             "supports": ["teta", "iota", "gama", "delta"]},
            {"codigo": "c-204", "tipo": "cifra", "atribucion": "Secretaria da Fazenda estadual",
             "medida": T("perda estimada de arrecadação por ano", "pérdida estimada de recaudación por año", "estimated annual revenue loss"),
             "valor": 48, "unidad": "milhões de reais por ano",
             "texto": T("A Secretaria da Fazenda estadual estimou perda de arrecadação de R$ 48 milhões por ano com a medida.",
                        "La Secretaría de Hacienda estatal estimó una pérdida de recaudación de 48 millones de reales (R$) por año con la medida.",
                        "The state finance department estimated a revenue loss of 48 million reais a year from the measure."),
             "fragmento": "A Fazenda estadual estima perda de R$ 48 milhões por ano em arrecadação.",
             "supports": ["delta", "zeta", "lambda"]},
            {"codigo": "c-205", "tipo": "cita", "atribucion": "Associação de Operadores de Apostas",
             "texto": T("A Associação de Operadores de Apostas disse que vai contestar a lei na Justiça por considerar que publicidade é matéria de competência federal.",
                        "La Asociación de Operadores de Apuestas dijo que impugnará la ley en los tribunales porque considera que la publicidad es materia de competencia federal.",
                        "The Association of Betting Operators said it will challenge the law in court, arguing that advertising is a matter of federal jurisdiction."),
             "fragmento": "A associação do setor disse que vai à Justiça por entender que o tema é de competência federal.",
             "supports": ["epsilon", "delta", "gama", "beta"]},
            {"codigo": "c-206", "tipo": "cifra", "atribucion": "Instituto de Defesa do Consumidor de Itaquara",
             "medida": T("famílias endividadas que citam apostas entre as causas da dívida", "hogares endeudados que citan apuestas entre las causas de la deuda", "indebted households citing betting among causes of debt"),
             "valor": 18, "unidad": "%",
             "texto": T("Pesquisa do Instituto de Defesa do Consumidor de Itaquara com 1.800 famílias endividadas indicou que 18% citam gastos com apostas entre as causas da dívida.",
                        "Una encuesta del Instituto de Defensa del Consumidor de Itaquara a 1.800 hogares endeudados indicó que el 18% cita gastos en apuestas entre las causas de la deuda.",
                        "A survey of 1,800 indebted households by the Itaquara Consumer Protection Institute found that 18% cite betting expenses among the causes of their debt."),
             "fragmento": "Entre 1.800 famílias endividadas ouvidas pelo instituto, 18% citam apostas entre as causas da dívida.",
             "supports": ["alfa", "beta", "eta", "teta"]},
            {"codigo": "c-207", "tipo": "cita", "atribucion": "deputados que votaram contra o projeto",
             "texto": T("Deputados que votaram contra o projeto afirmaram que a restrição reduz a receita de emissoras locais.",
                        "Diputados que votaron en contra del proyecto afirmaron que la restricción reduce los ingresos de las emisoras locales.",
                        "Lawmakers who voted against the bill said the restriction cuts revenue for local broadcasters."),
             "fragmento": "Deputados contrários disseram que emissoras locais perderão receita publicitária.",
             "supports": ["zeta", "capa", "epsilon"]},
        ],
        "brief": {
            "titulo": T("Assembleia de Itaquara aprova restrição à publicidade de apostas esportivas",
                        "Asamblea de Itaquara aprueba restricción a la publicidad de apuestas deportivas",
                        "Itaquara legislature approves limits on sports betting advertising"),
            "paragraphs": [
                [(T("A Assembleia Legislativa de Itaquara aprovou na quarta-feira, 30 de setembro, por 31 votos a 12, o projeto de lei estadual 214/2026, que restringe a publicidade de apostas esportivas de quota fixa.",
                    "La Asamblea Legislativa de Itaquara aprobó el miércoles 30 de septiembre, por 31 votos contra 12, el proyecto de ley estatal 214/2026, que restringe la publicidad de apuestas deportivas de cuota fija.",
                    "The Itaquara state legislature on Wednesday, Sept. 30, approved state bill 214/2026, which restricts advertising of fixed-odds sports betting, by 31 votes to 12."), ["c-201"]),
                 (T("O texto proíbe anúncios de apostas em rádio e televisão entre 6h e 22h e em eventos esportivos realizados em equipamentos públicos estaduais.",
                    "El texto prohíbe anuncios de apuestas en radio y televisión entre las 6 y las 22 horas y en eventos deportivos realizados en instalaciones públicas estatales.",
                    "The text bans betting ads on radio and television between 6 a.m. and 10 p.m. and at sporting events held in state-owned public venues."), ["c-202"]),
                 (T("O projeto segue para sanção ou veto do governador, que tem 15 dias úteis para decidir.",
                    "El proyecto pasa a la sanción o el veto del gobernador, que tiene 15 días hábiles para decidir.",
                    "The bill goes to the governor, who has 15 business days to sign or veto it."), ["c-203"])],
                [(T("Uma pesquisa do Instituto de Defesa do Consumidor de Itaquara com 1.800 famílias endividadas indicou que 18% citam gastos com apostas entre as causas da dívida, segundo o instituto.",
                    "Una encuesta del Instituto de Defensa del Consumidor de Itaquara a 1.800 hogares endeudados indicó que el 18% cita gastos en apuestas entre las causas de la deuda, según el instituto.",
                    "A survey of 1,800 indebted households by the Itaquara Consumer Protection Institute found that 18% cite betting expenses among the causes of their debt, according to the institute."), ["c-206"]),
                 (T("A Secretaria da Fazenda estadual estimou perda de arrecadação de R$ 48 milhões por ano com a medida.",
                    "La Secretaría de Hacienda estatal estimó una pérdida de recaudación de 48 millones de reales (R$) por año con la medida.",
                    "The state finance department estimated a revenue loss of 48 million reais a year from the measure."), ["c-204"])],
                [(T("A Associação de Operadores de Apostas disse que vai contestar a lei na Justiça por considerar que a publicidade é matéria de competência federal.",
                    "La Asociación de Operadores de Apuestas dijo que impugnará la ley en los tribunales porque considera que la publicidad es materia de competencia federal.",
                    "The Association of Betting Operators said it will challenge the law in court, arguing that advertising is a matter of federal jurisdiction."), ["c-205"]),
                 (T("Deputados que votaram contra o projeto afirmaram que a restrição reduz a receita de emissoras locais.",
                    "Diputados que votaron en contra del proyecto afirmaron que la restricción reduce los ingresos de las emisoras locales.",
                    "Lawmakers who voted against the bill said the restriction cuts revenue for local broadcasters."), ["c-207"])],
            ],
        },
        "commentary": False,
    },
    # ------------------------------------------------------------------ E3
    {
        "slug": "porto-anil-reintegracao-predio",
        "seccion": "justica", "secciones": ["justica", "sociedade"],
        "impacto": 70, "sensible": True, "excepcional": False, "razon": None,
        "fecha": 3,
        "titulo": T("Justiça de Itaquara determina reintegração de posse de prédio em Porto Anil",
                    "Justicia de Itaquara ordena la restitución de un edificio en Porto Anil",
                    "Itaquara court orders repossession of building in Porto Anil"),
        "articles": [
            ("alfa", 4, "Justiça manda desocupar prédio em Porto Anil; 210 famílias podem ficar sem teto"),
            ("beta", 4, "Famílias da ocupação Edifício Central têm 30 dias para deixar prédio"),
            ("eta", 4, "Defensoria recorre de ordem de despejo em Porto Anil"),
            ("iota", 3, "TJ de Itaquara determina reintegração de prédio ocupado no centro de Porto Anil"),
            ("delta", 3, "TJ ordena fim de invasão em prédio público de Porto Anil"),
            ("epsilon", 3, "Invasores têm 30 dias para deixar prédio do estado, decide Justiça"),
            ("zeta", 4, "Prédio invadido estava destinado a habitação social, diz secretaria"),
            ("lambda", 4, "Justiça de Itaquara determina reintegração de posse no centro de Porto Anil"),
            ("capa", 4, "Prefeitura promete aluguel social a famílias de prédio no centro de Porto Anil"),
            ("teta", 4, "Reintegração de posse: prefeitura conta 140 famílias em prédio de Porto Anil"),
            ("gama", 4, "Justiça determina reintegração de posse de prédio em Porto Anil"),
        ],
        "claims": [
            {"codigo": "c-301", "tipo": "que", "primaria": "Acórdão da 3ª Câmara Cível do TJ de Itaquara, 01/10/2026 (fictício)",
             "texto": T("A 3ª Câmara Cível do Tribunal de Justiça de Itaquara determinou em 1º de outubro de 2026 a reintegração de posse de um prédio de 12 andares no centro de Porto Anil, com prazo de 30 dias para saída voluntária.",
                        "La 3.ª Sala Civil del Tribunal de Justicia de Itaquara ordenó el 1 de octubre de 2026 la restitución de la posesión de un edificio de 12 pisos en el centro de Porto Anil, con un plazo de 30 días para la salida voluntaria.",
                        "The 3rd Civil Chamber of the Itaquara Court of Justice on Oct. 1, 2026 ordered the repossession of a 12-story building in downtown Porto Anil, with a 30-day deadline for voluntary departure."),
             "fragmento": "A 3ª Câmara Cível deu 30 dias para a saída voluntária das famílias do prédio de 12 andares.",
             "supports": ["alfa", "beta", "eta", "iota", "delta", "epsilon", "zeta", "lambda", "capa", "teta", "gama"]},
            {"codigo": "c-302", "tipo": "que", "primaria": "Registro de imóveis do patrimônio estadual de Itaquara (fictício)",
             "texto": T("O prédio pertence ao estado e estava sem uso desde 2019.",
                        "El edificio pertenece al estado y estaba sin uso desde 2019.",
                        "The building is state-owned and had been unused since 2019."),
             "fragmento": "O edifício, do patrimônio estadual, estava sem uso desde 2019.",
             "supports": ["alfa", "zeta", "delta", "lambda", "epsilon", "gama"]},
            {"codigo": "c-303", "tipo": "cuando",
             "texto": T("Um grupo de famílias permanece no imóvel desde 9 de agosto de 2026.",
                        "Un grupo de familias permanece en el inmueble desde el 9 de agosto de 2026.",
                        "A group of families has been living in the building since Aug. 9, 2026."),
             "fragmento": "As famílias estão no prédio desde 9 de agosto.",
             "supports": ["alfa", "beta", "eta", "iota", "capa", "teta", "gama", "lambda", "zeta"]},
            {"codigo": "c-304", "tipo": "cifra", "atribucion": "Movimento por Moradia de Porto Anil",
             "medida": T("famílias no prédio", "familias en el edificio", "families in the building"),
             "valor": 210, "unidad": "famílias",
             "texto": T("O Movimento por Moradia de Porto Anil informou que 210 famílias vivem no prédio.",
                        "El Movimiento por la Vivienda de Porto Anil informó que 210 familias viven en el edificio.",
                        "The Porto Anil Housing Movement said 210 families live in the building."),
             "fragmento": "O movimento de moradia afirma que 210 famílias vivem no prédio.",
             "supports": ["alfa", "beta", "eta"]},
            {"codigo": "c-305", "tipo": "cifra", "atribucion": "cadastro da prefeitura de Porto Anil",
             "medida": T("famílias no prédio", "familias en el edificio", "families in the building"),
             "valor": 140, "unidad": "famílias",
             "texto": T("O cadastro da prefeitura de Porto Anil registrou 140 famílias no prédio.",
                        "El registro de la alcaldía de Porto Anil contabilizó 140 familias en el edificio.",
                        "The Porto Anil city government's registry recorded 140 families in the building."),
             "fragmento": "O cadastro municipal registrou 140 famílias.",
             "supports": ["teta", "capa", "lambda", "iota"]},
            {"codigo": "c-306", "tipo": "cita", "atribucion": "prefeitura de Porto Anil",
             "texto": T("A prefeitura de Porto Anil disse que oferecerá aluguel social por seis meses às famílias cadastradas.",
                        "La alcaldía de Porto Anil dijo que ofrecerá un subsidio de alquiler por seis meses a las familias registradas.",
                        "The Porto Anil city government said it will offer six months of rent assistance to registered families."),
             "fragmento": "A prefeitura disse que vai oferecer aluguel social por seis meses às famílias cadastradas.",
             "supports": ["capa", "teta", "iota", "gama"]},
            {"codigo": "c-307", "tipo": "que", "primaria": "Petição da Defensoria Pública de Itaquara, 02/10/2026 (fictício)",
             "texto": T("A Defensoria Pública do estado recorreu da decisão em 2 de outubro e pediu a suspensão do prazo até a apresentação de um plano de realocação.",
                        "La Defensoría Pública del estado apeló la decisión el 2 de octubre y pidió suspender el plazo hasta que se presente un plan de reubicación.",
                        "The state Public Defender's Office appealed the decision on Oct. 2 and asked for the deadline to be suspended until a relocation plan is presented."),
             "fragmento": "A Defensoria recorreu e pediu que o prazo fique suspenso até haver plano de realocação.",
             "supports": ["eta", "beta", "alfa", "gama", "lambda"]},
            {"codigo": "c-308", "tipo": "cita", "atribucion": "Secretaria de Patrimônio do estado",
             "texto": T("A Secretaria de Patrimônio afirmou que o prédio está destinado a um projeto de habitação de interesse social, com licitação prevista para 2027.",
                        "La Secretaría de Patrimonio afirmó que el edificio está destinado a un proyecto de vivienda de interés social, con licitación prevista para 2027.",
                        "The state Property Department said the building is earmarked for a social housing project, with bidding planned for 2027."),
             "fragmento": "A secretaria disse que o prédio será usado em projeto de habitação social, com licitação em 2027.",
             "supports": ["zeta", "delta", "epsilon"]},
        ],
        "brief": {
            "titulo": T("Justiça de Itaquara determina reintegração de posse de prédio no centro de Porto Anil",
                        "Justicia de Itaquara ordena la restitución de un edificio en el centro de Porto Anil",
                        "Itaquara court orders repossession of building in downtown Porto Anil"),
            "paragraphs": [
                [(T("A 3ª Câmara Cível do Tribunal de Justiça de Itaquara determinou na quinta-feira, 1º de outubro, a reintegração de posse de um prédio de 12 andares no centro de Porto Anil, com prazo de 30 dias para saída voluntária.",
                    "La 3.ª Sala Civil del Tribunal de Justicia de Itaquara ordenó el jueves 1 de octubre la restitución de la posesión de un edificio de 12 pisos en el centro de Porto Anil, con un plazo de 30 días para la salida voluntaria.",
                    "The 3rd Civil Chamber of the Itaquara Court of Justice on Thursday, Oct. 1, ordered the repossession of a 12-story building in downtown Porto Anil, with a 30-day deadline for voluntary departure."), ["c-301"]),
                 (T("Um grupo de famílias permanece no imóvel desde 9 de agosto.",
                    "Un grupo de familias permanece en el inmueble desde el 9 de agosto.",
                    "A group of families has been living in the building since Aug. 9."), ["c-303"]),
                 (T("O prédio pertence ao estado e estava sem uso desde 2019.",
                    "El edificio pertenece al estado y estaba sin uso desde 2019.",
                    "The building is state-owned and had been unused since 2019."), ["c-302"])],
                [(T("O número de famílias no local difere conforme a fonte: o Movimento por Moradia de Porto Anil informou 210 famílias; o cadastro da prefeitura registrou 140.",
                    "El número de familias en el lugar difiere según la fuente: el Movimiento por la Vivienda de Porto Anil informó 210 familias; el registro de la alcaldía contabilizó 140.",
                    "The number of families at the site differs by source: the Porto Anil Housing Movement reported 210 families; the city registry recorded 140."), ["c-304", "c-305"]),
                 (T("A prefeitura de Porto Anil disse que oferecerá aluguel social por seis meses às famílias cadastradas.",
                    "La alcaldía de Porto Anil dijo que ofrecerá un subsidio de alquiler por seis meses a las familias registradas.",
                    "The Porto Anil city government said it will offer six months of rent assistance to registered families."), ["c-306"])],
                [(T("A Secretaria de Patrimônio do estado afirmou que o prédio está destinado a um projeto de habitação de interesse social, com licitação prevista para 2027.",
                    "La Secretaría de Patrimonio del estado afirmó que el edificio está destinado a un proyecto de vivienda de interés social, con licitación prevista para 2027.",
                    "The state Property Department said the building is earmarked for a social housing project, with bidding planned for 2027."), ["c-308"]),
                 (T("A Defensoria Pública do estado recorreu da decisão na sexta-feira, 2 de outubro, e pediu a suspensão do prazo até a apresentação de um plano de realocação.",
                    "La Defensoría Pública del estado apeló la decisión el viernes 2 de octubre y pidió suspender el plazo hasta que se presente un plan de reubicación.",
                    "The state Public Defender's Office appealed the decision on Friday, Oct. 2, and asked for the deadline to be suspended until a relocation plan is presented."), ["c-307"])],
            ],
        },
        "commentary": False,
    },
]

# ---------------------------------------------------------------- commentary
# Only descriptive and conceptual statements are filled in the demo. The rules
# forbid a language model from drafting explanatory or normative statements;
# those slots are shown as reserved for the human commentator.
SCHOLAR = {"nombre": "Comentadora A (fictícia)", "disciplina": "Economia política", "subcampo": "Recursos hídricos",
           "afiliacion": "Universidade Estadual de Itaquara (fictícia)", "orcid": None}
REVIEWER = {"nombre": "Revisor B (fictício)", "disciplina": "Economia política", "subcampo": "Finanças públicas",
            "afiliacion": "Instituto Federal do Planalto (fictício)", "orcid": None}

REFERENCES = [
    {"key": "r1", "tipo": "libro", "rol": "fundante", "autores": "Autor X (fictício)", "anio": 1998,
     "cita": "Autor X (fictício). Açudes e poder no interior de Itaquara. Editora Fictícia, 1998."},
    {"key": "r2", "tipo": "dato", "rol": "primaria", "autores": "Diário Oficial do Estado de Itaquara (fictício)", "anio": 2026,
     "cita": "Série de decretos de emergência por estiagem, 2016–2026 (dados fictícios)."},
    {"key": "r3", "tipo": "documento_oficial", "rol": "primaria", "autores": "Estado de Itaquara (fictício)", "anio": 2015,
     "cita": "Lei estadual de recursos hídricos n.º 1.234/2015 (fictícia)."},
    {"key": "r4", "tipo": "articulo", "rol": "estado_del_arte", "autores": "Autora Y (fictícia)", "anio": 2023,
     "cita": "Autora Y (fictícia). Emergência como estado de fato e como regime jurídico: uma revisão. Revista Fictícia de Teoria Política, 2023."},
    {"key": "r5", "tipo": "articulo", "rol": "disidente", "autores": "Autor Z (fictício)", "anio": 2021,
     "cita": "Autor Z (fictício). Contra a dicotomia fato/regime nas emergências. Cadernos Fictícios, 2021."},
]

STATEMENTS = [
    {"plano": "descriptivo", "estatus": "consenso", "escala": "larga_duracion", "disciplina": "História",
     "texto": T("A ocupação agrícola do interior de Itaquara se organizou, desde o século XIX, em torno de açudes de uso compartilhado entre irrigação e abastecimento humano; a disputa pela água nos períodos secos acompanha essa estrutura.",
                "La ocupación agrícola del interior de Itaquara se organizó, desde el siglo XIX, en torno a represas de uso compartido entre riego y abastecimiento humano; la disputa por el agua en los períodos secos acompaña esa estructura.",
                "Agricultural settlement of Itaquara's interior has been organized since the 19th century around reservoirs shared between irrigation and human supply; competition for water in dry periods follows that structure."),
     "claims": [], "refs": ["r1"]},
    {"plano": "descriptivo", "estatus": "consenso", "escala": "coyuntura", "disciplina": "Economia política",
     "texto": T("O estado decretou emergência por estiagem em quatro dos dez anos entre 2016 e 2025, segundo a série de decretos do Diário Oficial do Estado.",
                "El estado decretó emergencia por sequía en cuatro de los diez años entre 2016 y 2025, según la serie de decretos del Diario Oficial del Estado.",
                "The state declared a drought emergency in four of the ten years between 2016 and 2025, according to the series of decrees in the State Official Gazette."),
     "claims": [], "refs": ["r2"]},
    {"plano": "descriptivo", "estatus": "consenso", "escala": "acontecimiento", "disciplina": "Direito administrativo",
     "texto": T("O decreto se apoia na lei estadual de recursos hídricos, que permite restringir captações quando há emergência declarada.",
                "El decreto se apoya en la ley estatal de recursos hídricos, que permite restringir captaciones cuando hay emergencia declarada.",
                "The decree relies on the state water resources law, which allows withdrawals to be restricted when an emergency has been declared."),
     "claims": ["c-101", "c-102"], "refs": ["r3"]},
    {"plano": "conceptual", "estatus": "disputa", "escala": "transversal", "disciplina": "Filosofia política",
     "texto": T("“Emergência” aparece aqui em dois sentidos: como estado de fato (falta de água) e como regime jurídico que suspende procedimentos ordinários, como a licitação. Os títulos de cada polo enfatizam um sentido e tratam o outro como secundário.",
                "“Emergencia” aparece aquí en dos sentidos: como estado de hecho (falta de agua) y como régimen jurídico que suspende procedimientos ordinarios, como la licitación. Los titulares de cada polo enfatizan un sentido y tratan el otro como secundario.",
                "“Emergency” is used here in two senses: as a state of fact (lack of water) and as a legal regime that suspends ordinary procedures such as competitive bidding. Each pole's headlines stress one sense and treat the other as secondary."),
     "claims": ["c-102"], "refs": ["r4", "r5"]},
]
TRADITION = T("Economia política institucionalista (declaração fictícia)",
              "Economía política institucionalista (declaración ficticia)",
              "Institutionalist political economy (fictional declaration)")
OPEN_QUESTIONS = [
    {"razon": "datos_inexistentes",
     "texto": T("Quantas famílias estão sem abastecimento regular de água?",
                "¿Cuántas familias están sin abastecimiento regular de agua?",
                "How many families are without regular water supply?"),
     "por": T("As fontes divergem e não há registro independente consolidado.",
              "Las fuentes difieren y no hay un registro independiente consolidado.",
              "Sources differ and there is no consolidated independent record.")},
    {"razon": "sin_estudios",
     "texto": T("As compras emergenciais feitas nas estiagens anteriores foram auditadas?",
                "¿Se auditaron las compras de emergencia realizadas en sequías anteriores?",
                "Were emergency purchases made during previous droughts audited?"),
     "por": T("Não há estudos nem relatórios públicos consolidados sobre essas compras.",
              "No hay estudios ni informes públicos consolidados sobre esas compras.",
              "There are no studies or consolidated public reports on those purchases.")},
]
DISCIPLINES = [
    ("História", "historia", T("Como se formou a disputa pela água no interior do estado?", "¿Cómo se formó la disputa por el agua en el interior del estado?", "How did competition for water in the state's interior take shape?")),
    ("Economia política", "ciencias_sociales", T("Com que frequência o estado recorre a emergências e com que efeitos fiscais?", "¿Con qué frecuencia recurre el estado a emergencias y con qué efectos fiscales?", "How often does the state resort to emergencies, and with what fiscal effects?")),
    ("Direito administrativo", "derecho", T("O que o regime de emergência permite e o que não permite?", "¿Qué permite y qué no permite el régimen de emergencia?", "What does the emergency regime allow and not allow?")),
    ("Hidrologia", "ciencias_naturales", T("Qual é a disponibilidade hídrica real dos reservatórios?", "¿Cuál es la disponibilidad hídrica real de los embalses?", "What is the actual water availability of the reservoirs?")),
    ("Filosofia política", "filosofia", T("O que significa “emergência” no vocabulário de cada polo?", "¿Qué significa “emergencia” en el vocabulario de cada polo?", "What does “emergency” mean in each pole's vocabulary?")),
]
GAP = ("Hidrologia", T("Sem comentador disponível no painel de demonstração.", "Sin comentador disponible en el panel de demostración.", "No commentator available on the demo panel."))
