"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-05 23:18:55.123424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_usage_daily',
    sa.Column('dia', sa.Date(), nullable=False),
    sa.Column('preguntas', sa.Integer(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('costo_centavos', sa.Float(), nullable=False),
    sa.Column('rechazos_verificador', sa.Integer(), nullable=False),
    sa.Column('negativas', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('dia')
    )
    op.create_table('country',
    sa.Column('id', sa.String(length=2), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('idiomas', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('zona_horaria', sa.String(length=64), nullable=False),
    sa.Column('fecha_inicializacion', sa.Date(), nullable=False),
    sa.Column('contexto', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('data_gaps', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('fuente_primaria', sa.String(length=300), nullable=False),
    sa.Column('metodo', sa.Text(), nullable=False),
    sa.Column('fecha_corte', sa.Date(), nullable=False),
    sa.Column('unidad', sa.String(length=40), nullable=False),
    sa.Column('cobertura_territorial', sa.String(length=120), nullable=False),
    sa.Column('licencia', sa.String(length=80), nullable=False),
    sa.Column('verificada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('datos', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('framing_annotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_tipo', sa.String(length=12), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('terminos_cargados', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('marco', sa.String(length=200), nullable=True),
    sa.Column('carga_emocional', sa.Float(), nullable=True),
    sa.Column('afirmaciones_omitidas', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('human_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_tipo', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('revisor', sa.String(length=120), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('comentarios', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('cita', sa.Text(), nullable=False),
    sa.Column('doi_o_url', sa.String(length=400), nullable=True),
    sa.Column('autores', sa.String(length=400), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('revision_por_pares', sa.Boolean(), nullable=False),
    sa.Column('indicador_influencia', sa.Float(), nullable=True),
    sa.Column('verificada_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verificada_por', sa.String(length=120), nullable=False),
    sa.Column('es_ficticia', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_tipo', sa.String(length=30), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('campo', sa.String(length=40), nullable=False),
    sa.Column('idioma', sa.String(length=5), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('claim_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('metodo', sa.String(length=20), nullable=False),
    sa.Column('revisor', sa.String(length=120), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("metodo = 'maquina_sin_revisar' OR revisor IS NOT NULL", name='ck_tr_reviewer'),
    sa.CheckConstraint("metodo IN ('humano','maquina_revisada','maquina_sin_revisar')", name='ck_tr_method'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_tipo', 'source_id', 'campo', 'idioma')
    )
    op.create_table('cleavage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.String(length=2), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('es_hipotesis', sa.Boolean(), nullable=False),
    sa.Column('peso_relevancia', sa.Float(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('vigente_desde', sa.Date(), nullable=False),
    sa.Column('vigente_hasta', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_id', 'slug', 'vigente_desde')
    )
    op.create_table('cultural_reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.String(length=2), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('familia', sa.String(length=20), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('justificacion', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.String(length=2), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('semana_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('semana_fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('corte_ingesta', sa.DateTime(timezone=True), nullable=False),
    sa.Column('publicacion_prevista', sa.DateTime(timezone=True), nullable=False),
    sa.Column('publicada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('es_demo', sa.Boolean(), nullable=False),
    sa.Column('aprobada_por', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_id', 'numero')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.String(length=2), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('titulo_provisional', sa.String(length=300), nullable=False),
    sa.Column('seccion', sa.String(length=30), nullable=False),
    sa.Column('secciones_tocadas', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('impacto', sa.Integer(), nullable=False),
    sa.Column('sensible', sa.Boolean(), nullable=False),
    sa.Column('tema_excepcional', sa.Boolean(), nullable=False),
    sa.Column('razon_inclusion', sa.Text(), nullable=True),
    sa.Column('razon_inclusion_confirmada_por', sa.String(length=120), nullable=True),
    sa.Column('es_ficticio', sa.Boolean(), nullable=False),
    sa.CheckConstraint('tema_excepcional = false OR razon_inclusion IS NOT NULL', name='ck_event_exceptional_reason'),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('exclusion_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.String(length=2), nullable=False),
    sa.Column('elemento', sa.String(length=200), nullable=False),
    sa.Column('colores', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('motivo', sa.String(length=20), nullable=False),
    sa.Column('confirmado', sa.Boolean(), nullable=False),
    sa.Column('vigente_desde', sa.Date(), nullable=False),
    sa.Column('vigente_hasta', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loaded_term',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.String(length=2), nullable=False),
    sa.Column('idioma', sa.String(length=5), nullable=False),
    sa.Column('termino', sa.String(length=80), nullable=False),
    sa.Column('patron', sa.String(length=200), nullable=False),
    sa.Column('alternativa', sa.String(length=200), nullable=True),
    sa.Column('nota', sa.Text(), nullable=False),
    sa.Column('permitido_si', sa.String(length=30), nullable=False),
    sa.Column('vigente_desde', sa.Date(), nullable=False),
    sa.Column('vigente_hasta', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outlet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.String(length=2), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('alcance', sa.String(length=20), nullable=False),
    sa.Column('region', sa.String(length=40), nullable=True),
    sa.Column('audiencia_estimada', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=300), nullable=True),
    sa.Column('idioma', sa.String(length=5), nullable=False),
    sa.Column('es_fuente_oficial', sa.Boolean(), nullable=False),
    sa.Column('feeds', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('es_ficticio', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scholar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.String(length=2), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('disciplina', sa.String(length=80), nullable=False),
    sa.Column('subcampo', sa.String(length=120), nullable=True),
    sa.Column('afiliacion', sa.String(length=200), nullable=False),
    sa.Column('pais', sa.String(length=2), nullable=False),
    sa.Column('orcid', sa.String(length=40), nullable=True),
    sa.Column('idiomas', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('activo_desde', sa.Date(), nullable=False),
    sa.Column('activo_hasta', sa.Date(), nullable=True),
    sa.Column('es_ficticio', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('theme_country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.String(length=2), nullable=False),
    sa.Column('tipografia_titulares', sa.String(length=120), nullable=False),
    sa.Column('color_marca', sa.String(length=9), nullable=False),
    sa.Column('textura_id', sa.String(length=60), nullable=True),
    sa.Column('direccion_foto', sa.Text(), nullable=False),
    sa.Column('tokens', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('provisional', sa.Boolean(), nullable=False),
    sa.Column('vigente_desde', sa.Date(), nullable=False),
    sa.Column('vigente_hasta', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outlet_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=600), nullable=False),
    sa.Column('titular', sa.String(length=500), nullable=False),
    sa.Column('cuerpo', sa.Text(), nullable=True),
    sa.Column('cuerpo_permitido', sa.Boolean(), nullable=False),
    sa.Column('fecha_pub', sa.DateTime(timezone=True), nullable=False),
    sa.Column('autor', sa.String(length=200), nullable=True),
    sa.Column('idioma', sa.String(length=5), nullable=False),
    sa.Column('hash_texto', sa.String(length=64), nullable=False),
    sa.Column('es_ficticio', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlet.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash_texto')
    )
    op.create_table('chat_session',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('edition_id', sa.Integer(), nullable=False),
    sa.Column('idioma', sa.String(length=5), nullable=False),
    sa.Column('modo_factual', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['edition_id'], ['edition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_suggestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edition_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['edition_id'], ['edition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('texto_normalizado', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('verificable', sa.Boolean(), nullable=False),
    sa.Column('modo', sa.String(length=10), nullable=True),
    sa.Column('atribucion', sa.String(length=300), nullable=True),
    sa.Column('medida', sa.String(length=120), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(length=40), nullable=True),
    sa.Column('fuente_primaria', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('commentary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('edition_id', sa.Integer(), nullable=False),
    sa.Column('scholar_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('tradicion_declarada', sa.String(length=300), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('idioma', sa.String(length=5), nullable=False),
    sa.Column('cargado_por', sa.String(length=120), nullable=False),
    sa.CheckConstraint("tipo = 'fondo'", name='ck_commentary_only_background'),
    sa.ForeignKeyConstraint(['edition_id'], ['edition.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['scholar_id'], ['scholar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disciplinary_gap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('disciplina', sa.String(length=80), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discipline_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('disciplina', sa.String(length=80), nullable=False),
    sa.Column('familia', sa.String(length=40), nullable=False),
    sa.Column('pregunta', sa.Text(), nullable=False),
    sa.Column('justificacion', sa.Text(), nullable=False),
    sa.Column('propuesto_por', sa.String(length=10), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edition_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edition_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('version_evento', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['edition_id'], ['edition.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edition_id', 'event_id')
    )
    op.create_table('neutral_brief',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('edition_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('modelo', sa.String(length=80), nullable=False),
    sa.Column('prompt_version', sa.String(length=40), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('verificacion', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['edition_id'], ['edition.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outlet_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outlet_id', sa.Integer(), nullable=False),
    sa.Column('cleavage_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('ic_inferior', sa.Float(), nullable=False),
    sa.Column('ic_superior', sa.Float(), nullable=False),
    sa.Column('metodo', sa.String(length=200), nullable=False),
    sa.Column('n_articulos_base', sa.Integer(), nullable=False),
    sa.Column('provisional', sa.Boolean(), nullable=False),
    sa.Column('vigente_desde', sa.Date(), nullable=False),
    sa.Column('vigente_hasta', sa.Date(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ic_inferior <= score AND score <= ic_superior', name='ck_outlet_ic'),
    sa.CheckConstraint('score >= -1 AND score <= 1', name='ck_outlet_score_range'),
    sa.ForeignKeyConstraint(['cleavage_id'], ['cleavage.id'], ),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outlet_reliability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outlet_id', sa.Integer(), nullable=False),
    sa.Column('correcciones_publicadas', sa.Integer(), nullable=False),
    sa.Column('verificaciones_fallidas', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ownership_funding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outlet_id', sa.Integer(), nullable=False),
    sa.Column('propietario', sa.String(length=200), nullable=False),
    sa.Column('grupo_economico', sa.String(length=200), nullable=True),
    sa.Column('publicidad_federal_monto', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('periodo', sa.String(length=20), nullable=False),
    sa.Column('fuente_dato', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('palette',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.String(length=2), nullable=False),
    sa.Column('cleavage_id', sa.Integer(), nullable=False),
    sa.Column('asignacion_polo_color', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('contraste_verificado', sa.Boolean(), nullable=False),
    sa.Column('prueba_ciega_fecha', sa.Date(), nullable=True),
    sa.Column('provisional', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cleavage_id'], ['cleavage.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pole',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cleavage_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('etiqueta', sa.String(length=160), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cleavage_id'], ['cleavage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reference_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('cleavage_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('ic_inferior', sa.Float(), nullable=False),
    sa.Column('ic_superior', sa.Float(), nullable=False),
    sa.Column('metodo', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['cleavage_id'], ['cleavage.id'], ),
    sa.ForeignKeyConstraint(['reference_id'], ['cultural_reference.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scholar_disclosure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scholar_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('entidad', sa.String(length=200), nullable=False),
    sa.Column('periodo', sa.String(length=40), nullable=False),
    sa.Column('fuente', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['scholar_id'], ['scholar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scholar_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scholar_id', sa.Integer(), nullable=False),
    sa.Column('cleavage_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('ic_inferior', sa.Float(), nullable=False),
    sa.Column('ic_superior', sa.Float(), nullable=False),
    sa.Column('metodo', sa.String(length=200), nullable=False),
    sa.Column('vigente_desde', sa.Date(), nullable=False),
    sa.Column('vigente_hasta', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['cleavage_id'], ['cleavage.id'], ),
    sa.ForeignKeyConstraint(['scholar_id'], ['scholar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('theme_blind_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theme_country_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('muestra_por_polo', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('reconocimiento', sa.Float(), nullable=False),
    sa.Column('inclinacion_percibida', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['theme_country_id'], ['theme_country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('theme_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theme_country_id', sa.Integer(), nullable=False),
    sa.Column('seccion', sa.String(length=30), nullable=False),
    sa.Column('tono_derivado', sa.String(length=9), nullable=False),
    sa.Column('uso_textura', sa.Boolean(), nullable=False),
    sa.Column('direccion_imagen', sa.Text(), nullable=False),
    sa.Column('austeridad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['theme_country_id'], ['theme_country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('edition_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('forma', sa.String(length=40), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('brief_version', sa.Integer(), nullable=False),
    sa.Column('fecha_corte', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('spec', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.CheckConstraint('nivel BETWEEN 0 AND 2', name='ck_visual_level_v1'),
    sa.ForeignKeyConstraint(['edition_id'], ['edition.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visual_gap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('dato_faltante', sa.Text(), nullable=False),
    sa.Column('motivo', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_event',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('score_similitud', sa.Float(), nullable=False),
    sa.Column('asignacion', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'event_id')
    )
    op.create_table('blindspot_flag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edition_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('pole_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=160), nullable=False),
    sa.Column('diferencia_cobertura', sa.Float(), nullable=False),
    sa.Column('umbral_usado', sa.Float(), nullable=False),
    sa.Column('impacto_estimado', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['edition_id'], ['edition.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['pole_id'], ['pole.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brief_sentence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brief_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('parrafo', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('claim_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['brief_id'], ['neutral_brief.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brief_id', 'orden')
    )
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('rol', sa.String(length=10), nullable=False),
    sa.Column('contenido', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('verificacion', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_support',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('fragmento_fuente', sa.Text(), nullable=False),
    sa.Column('postura', sa.String(length=10), nullable=False),
    sa.Column('confianza', sa.Float(), nullable=False),
    sa.CheckConstraint("postura IN ('afirma','contradice','matiza')", name='ck_postura'),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commentary_statement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commentary_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('plano', sa.String(length=14), nullable=False),
    sa.Column('estatus_epistemico', sa.String(length=14), nullable=False),
    sa.Column('escala_temporal', sa.String(length=16), nullable=False),
    sa.Column('disciplina', sa.String(length=80), nullable=False),
    sa.Column('claim_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('reference_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('mecanismo', sa.Text(), nullable=True),
    sa.Column('evidencia_que_refutaria', sa.Text(), nullable=True),
    sa.Column('autoria', sa.String(length=10), nullable=False),
    sa.CheckConstraint("estatus_epistemico <> 'hipotesis' OR (mecanismo IS NOT NULL AND evidencia_que_refutaria IS NOT NULL)", name='ck_hypothesis_refutation'),
    sa.CheckConstraint("estatus_epistemico <> 'hipotesis' OR plano = 'explicativo'", name='ck_hypothesis_plane'),
    sa.CheckConstraint("plano NOT IN ('explicativo','normativo') OR autoria = 'humano'", name='ck_no_llm_explanatory'),
    sa.ForeignKeyConstraint(['commentary_id'], ['commentary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coverage_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('pole_id', sa.Integer(), nullable=False),
    sa.Column('dia', sa.Date(), nullable=False),
    sa.Column('articulos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['pole_id'], ['pole.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coverage_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edition_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('pole_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=160), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('medios_que_cubren', sa.Integer(), nullable=False),
    sa.Column('medios_activos_del_polo', sa.Integer(), nullable=False),
    sa.Column('pct', sa.Float(), nullable=False),
    sa.Column('pct_ponderado_audiencia', sa.Float(), nullable=True),
    sa.CheckConstraint('medios_que_cubren <= medios_activos_del_polo', name='ck_cov_denominator'),
    sa.ForeignKeyConstraint(['edition_id'], ['edition.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['pole_id'], ['pole.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('framing_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('pole_id', sa.Integer(), nullable=False),
    sa.Column('article_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('no_menciona', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['pole_id'], ['pole.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('open_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commentary_id', sa.Integer(), nullable=False),
    sa.Column('pregunta', sa.Text(), nullable=False),
    sa.Column('razon', sa.String(length=30), nullable=False),
    sa.Column('anadida_por', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['commentary_id'], ['commentary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peer_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commentary_id', sa.Integer(), nullable=False),
    sa.Column('revisor_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('objeciones', sa.Text(), nullable=False),
    sa.Column('estatus_corregidos', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('fuentes_ineludibles_omitidas', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['commentary_id'], ['commentary.id'], ),
    sa.ForeignKeyConstraint(['revisor_id'], ['scholar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visual_control',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visual_id', sa.Integer(), nullable=False),
    sa.Column('perspectiva', sa.String(length=12), nullable=False),
    sa.Column('pregunta_que_responde', sa.Text(), nullable=False),
    sa.Column('valor_por_defecto', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['visual_id'], ['visual.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visual_encoding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visual_id', sa.Integer(), nullable=False),
    sa.Column('canal', sa.String(length=12), nullable=False),
    sa.Column('variable', sa.String(length=80), nullable=False),
    sa.Column('escala', sa.String(length=40), nullable=False),
    sa.Column('origen_eje', sa.Float(), nullable=True),
    sa.Column('corte_senalado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['visual_id'], ['visual.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visual_justification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visual_id', sa.Integer(), nullable=False),
    sa.Column('pregunta_lector', sa.Text(), nullable=False),
    sa.Column('forma_de_la_informacion', sa.String(length=80), nullable=False),
    sa.Column('filtro_superado', sa.String(length=80), nullable=False),
    sa.Column('alternativa_textual_descartada', sa.Text(), nullable=False),
    sa.Column('aprobado_por', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['visual_id'], ['visual.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visual_id')
    )
    op.create_table('visual_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visual_id', sa.Integer(), nullable=False),
    sa.Column('revisor', sa.String(length=120), nullable=False),
    sa.Column('checklist', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('comentarios', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['visual_id'], ['visual.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('control_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('control_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=20), nullable=False),
    sa.Column('usos', sa.Integer(), nullable=False),
    sa.Column('vistas', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['visual_control.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visual_mark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visual_id', sa.Integer(), nullable=False),
    sa.Column('claim_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('coverage_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('fuente', sa.String(length=300), nullable=False),
    sa.Column('ic_inferior', sa.Float(), nullable=True),
    sa.Column('ic_superior', sa.Float(), nullable=True),
    sa.Column('denominador', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['coverage_snapshot_id'], ['coverage_snapshot.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['visual_id'], ['visual.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visual_mark')
    op.drop_table('control_usage')
    op.drop_table('visual_review')
    op.drop_table('visual_justification')
    op.drop_table('visual_encoding')
    op.drop_table('visual_control')
    op.drop_table('peer_review')
    op.drop_table('open_question')
    op.drop_table('framing_summary')
    op.drop_table('coverage_snapshot')
    op.drop_table('coverage_daily')
    op.drop_table('commentary_statement')
    op.drop_table('claim_support')
    op.drop_table('chat_message')
    op.drop_table('brief_sentence')
    op.drop_table('blindspot_flag')
    op.drop_table('article_event')
    op.drop_table('visual_gap')
    op.drop_table('visual')
    op.drop_table('theme_section')
    op.drop_table('theme_blind_test')
    op.drop_table('scholar_position')
    op.drop_table('scholar_disclosure')
    op.drop_table('reference_position')
    op.drop_table('pole')
    op.drop_table('palette')
    op.drop_table('ownership_funding')
    op.drop_table('outlet_reliability')
    op.drop_table('outlet_position')
    op.drop_table('neutral_brief')
    op.drop_table('edition_event')
    op.drop_table('discipline_map')
    op.drop_table('disciplinary_gap')
    op.drop_table('commentary')
    op.drop_table('claim')
    op.drop_table('chat_suggestion')
    op.drop_table('chat_session')
    op.drop_table('article')
    op.drop_table('theme_country')
    op.drop_table('scholar')
    op.drop_table('outlet')
    op.drop_table('loaded_term')
    op.drop_table('exclusion_list')
    op.drop_table('event')
    op.drop_table('edition')
    op.drop_table('cultural_reference')
    op.drop_table('cleavage')
    op.drop_table('translation')
    op.drop_table('reference')
    op.drop_table('human_review')
    op.drop_table('framing_annotation')
    op.drop_table('dataset')
    op.drop_table('country')
    op.drop_table('chat_usage_daily')
    # ### end Alembic commands ###
