"""dispute channel

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-05 23:24:29.998913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_tipo', sa.String(length=30), nullable=False),
    sa.Column('target_ref', sa.String(length=80), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('evidencia', sa.Text(), nullable=False),
    sa.Column('contacto', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('resolucion', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dispute')
    # ### end Alembic commands ###
